### ISSUE TITLE
hasPermission() crashes when called in background service

### ISSUE THREAD

**Issue by jonasbjurhult** [stgrosshh/tipermissions#1]
See log:

03-10 12:07:50.883  8873  8887 I TiAPI   :  SERVICE: Android Background Location Service start
03-10 12:07:50.886  8873  8887 D Module  : Loading module: permissions -> Resources/permissions.js
03-10 12:07:50.898  8873  8887 D TipermissionsModule: (KrollRuntimeThread) [657,1798] Ti Permissions Module ctor
03-10 12:07:50.900  8873  8887 D TipermissionsModule: (KrollRuntimeThread) [3,1801] check for granted permission: android.permission.ACCESS_FINE_LOCATION
03-10 12:07:50.902  8873  8887 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
03-10 12:07:50.924  8873  8887 W System.err:    at android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:387)
03-10 12:07:50.924  8873  8887 W System.err:    at ti.permissions.TipermissionsModule.hasPermission(TipermissionsModule.java:155)
03-10 12:07:50.924  8873  8887 W System.err:    at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
03-10 12:07:50.924  8873  8887 W System.err:    at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
03-10 12:07:50.924  8873  8887 W System.err:    at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:319)
03-10 12:07:50.924  8873  8887 W System.err:    at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
03-10 12:07:50.924  8873  8887 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:98)
03-10 12:07:50.924  8873  8887 W System.err:    at android.os.Looper.loop(Looper.java:148)
03-10 12:07:50.924  8873  8887 W System.err:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)
03-10 12:07:50.936  8873  8873 W TiExceptionHandler: (main) [36,1837] Activity is null or already finishing, skipping dialog.
03-10 12:07:50.938  8873  8887 E V8Exception: Exception occurred at permissions.js:42: Uncaught Error: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference

**Comment by stgrosshh** [comment]
Please see http://stackoverflow.com/questions/32292675/how-to-request-permissions-from-a-service-in-android-marshmallow

Based on that info, I think we can provide a way to check for granted permissions, but the preparation work to be able to request has to be implemented in your code then.

Can you please provide a Titanium code example for easier reproduction and testing.

Thanks
 Stefan
